apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: wolfs-io
  namespace: argocd
spec:
  generators:
  - merge:
      mergeKeys:
        - name
      generators:
        - clusters: {}
        - merge:
            mergeKeys:
              - path.basename
              - name
            generators:
              - git:
                  repoURL: https://github.com/joshrwolf/aoa-testing.git
                  revision: main
                  files:
                    - path: apps/**/.cfg.yaml
              - git:
                  repoURL: https://github.com/joshrwolf/aoa-testing.git
                  revision: main
                  files:
                    - path: env/wolfs.io/clusters/**/config.yaml
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{name}}-{{path.basename}}-wolfs-io"
      name: "{{name}}-{{path.basename}}-wolfs-io"
      namespace: argocd
    spec:
      ignoreDifferences:
      - group: argoproj.io
        jsonPointers:
        - /status
        kind: Application
      project: default
      source:
        path: "{{path}}"
        repoURL: https://github.com/joshrwolf/aoa-testing.git
        targetRevision: main

      destination:
        server: "{{server}}"

      syncPolicy:
        automated:
          prune: false
          allowEmpty: false
          selfHeal: false

